### ISSUE TITLE
go code generated in wrong folder

### ISSUE THREAD

**Issue by yoadwo** [Clever/wag#293]
hey
experimenting with your project, i noticed that the folder _gen-go_ and _gen-js_ are not created in the same place.
from our GOPATH _workspace/src_: we  run _make generate_ from path _workspace/src/test/wag-1_. 
**expected:** both _gen-js_ and _gen-go_ to be created at the project folder
**actual:** the _gen-js_ is created in the same folder, and _gen-go_ is created at _workspace/src/gen-go_.

digging into [wag.mk](https://github.com/Clever/dev-handbook/blob/master/make/wag.mk) i found this line:
`bin/wag -go-package $(2)/gen-go -js-path ./gen-js -file $(1)`. i don't really understand where $2 came from, so tried changing it to look more like _gen-js_:
`bin/wag -go-package ./gen-go -js-path ./gen-js -file $(1)`
but still it is created at same place. could it be that the flag responsible for `go-package` is buggy?

**What version of Go are you using (go version)?**
1.13.8

**Comment by aastein** [comment]
Hi, the argument to `-go-package` should be the go package name. For example `github.com/Clever/my-service`.
